### PR TITLE
Add Create Payment Request Page

### PR DESCRIPTION
**Pull request by Publicker**
This pull request introduces the Create Payment Request page, along with numerous changes in various components to ensure its proper functionality. Apologies for the size of the PR, but all the work needed to be combined to make the page functional. There are two stories where the page can be tested:

- UI/CreatePaymentRequestPage - For testing the look and feel
- Functional/Create Payment Request - For testing functionality, including the creation of payment requests.

To test the functionality in the second story, use the Storybook controls to provide the following props:

- `token`: Your user token
- `merchantId`: Your merchant ID
- `apiUrl`: API that the component should use (ensure that your token was created for use in the same environment as the API)

A video demonstrating how to obtain these values is attached (low quality due to GitHub's 10MB limit).

https://github.com/nofrixion/nofrixion.webcomponents/assets/52673485/0dabb5ef-10d1-4740-a5cb-478be4e218be

### CODE REVIEW

**Review by donalnofrixion — APPROVED** [review]

**Comment by donalnofrixion** [comment]
Hey @Publicker Just spotted a bug. If you create a payment request with an amount that has a cent amount (e.g. 12.99) the create request sends 12 instead of 12.99.

**Comment by Publicker** [comment]
> Hey @Publicker Just spotted a bug. If you create a payment request with an amount that has a cent amount (e.g. 12.99) the create request sends 12 instead of 12.99.

@donalnofrixion Thanks for testing and reporting it! Fixed applied in [this commit](https://github.com/nofrixion/nofrixion.webcomponents/pull/31/commits/0898e69dd2977f27f33c57152776823cd6dfe73f) and already deployed too.

Could you try again ([link to Storybook](https://6410c09a16b1ae3112580b1c-ufisanktxl.chromatic.com/?path=/story/functional-create-payment-request--showcase) and let me know your results? Thanks!

**Comment by donalnofrixion** [comment]
> > Hey @Publicker Just spotted a bug. If you create a payment request with an amount that has a cent amount (e.g. 12.99) the create request sends 12 instead of 12.99.
> 
> @donalnofrixion Thanks for testing and reporting it! Fixed applied in [this commit](https://github.com/nofrixion/nofrixion.webcomponents/pull/31/commits/0898e69dd2977f27f33c57152776823cd6dfe73f) and already deployed too.
> 
> Could you try again ([link to Storybook](https://6410c09a16b1ae3112580b1c-ufisanktxl.chromatic.com/?path=/story/functional-create-payment-request--showcase) and let me know your results? Thanks!

Looks good 👍

**Review by pabloi-nf — CHANGES_REQUESTED** [review]
There is a weird animation on the email validation.

https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/b2a0c1be-cd7a-45de-abd1-4fac497c9868

**Comment by Publicker** [comment]
> There is a weird animation on the email validation.
> 
> 
> 
> https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/b2a0c1be-cd7a-45de-abd1-4fac497c9868
> 
> 
> 
> 

Thanks @pabloi-nf - Will look into it.

**Review by pabloi-nf — APPROVED** [review]

**Pull request merged**
