### PR TITLE
[MOOV-2034]: Added server- and client-side validations on PR creation

### PR DESCRIPTION
**Pull request by agranillonf**
* Minimum PISP amount client-side validation has been added to the payment request creation page, as well as a more user-friendly server-side validation message display logic.
* The _"Review payment request"_ button only shows when all fields are valid.
* Fixed Delete PR button UI.
* If no payment method is chosen on payment request creation, an alert is shown prompting user to choose one.
* Fixed payment method icon sizes on desktop and mobile.
* Fixed PR contact last name showing as 'undefined' when leaving it empty on creation.

### CODE REVIEW

**Review by arifmatin — APPROVED** [review]

**Review by pabloi-nfxn — CHANGES_REQUESTED** [review]
The text should say:
"Please try again. If the problem persists, you can contact us at support@nofrixion.com"

The box makes a weird animation when the button is pressed again. 
The animation should be just a subtle slide from above with fade in.

https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/cee5c22d-1f42-4802-9daf-ed65688b22ce

In the inline validation, the box should not dissapear and appear again everytime another switch is on or off.

https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/607ece9f-a35d-435f-aebe-3ee669f39c61

**Comment by agranillonf** [comment]
@pabloi-nf Animations have been fixed.

**Review by sauravmaiti22 — APPROVED** [review]

**Review by donalnofrixion — APPROVED** [review]

**Review by pabloi-nfxn — CHANGES_REQUESTED** [review]
Is it possible to avoid the stretching of the text when the message changes?
This can be an odd case, but if we leave it working properly we can avoid future more common scenarios.


https://github.com/nofrixion/nofrixion.webcomponents/assets/127946572/2eb7ca1c-8b5f-4c52-ae8c-e5066580e59f



I couldn't replicate the server error message again. Is it possible to upload a video?

**Comment by agranillonf** [comment]
@pabloi-nf Here's a **staged** scenario, forcing the server error alert to display:

https://github.com/nofrixion/nofrixion.webcomponents/assets/114026805/f831f978-3237-460d-8897-5e78c607fb9a

**Review by pabloi-nfxn — APPROVED** [review]

**Pull request merged**
